### ISSUE TITLE
[BUG]: OneKey Browser (WebView) doesn't open Wallets list when clicking WalletConnect Modal's Select Wallet button on Android

### ISSUE THREAD

**Issue by aramkgh** [OneKeyHQ/app-monorepo#6804]
- [x] I checked to make sure that this issue has not already been filed

Title: OneKey Browser (WebView) doesn't open Wallets list when clicking WalletConnect Modal's Select Wallet button on Android

Describe the bug
The OneKey browser on Android fails to load a deeplink when using the WalletConnect modal. Specifically, after clicking the "Select Wallet" button, the browser throws an error and does not open the available wallets on the device.

To Reproduce
Open the OneKey browser on an Android device (Note: iOS does not have the "Select Wallet" button, but it works when selecting OneKey from the list).
Visit [app.gmx.io](https://app.gmx.io/). (Any dapp)
Click "Connect Wallet" in the header.
Choose "WalletConnect."
Click "Select Wallet."
Expected behavior: A list of available wallets installed on the device should appear.
Actual behavior: An error occurs, and the page displays the message:
"Webpage not available, the webpage at wc:... could not be loaded because: net: ERR_UNKNOWN_URL_SCHEME."
Expected behavior
The "Select Wallet" modal should display a list of available wallets on the device, allowing the user to choose and continue the connection.

Screenshots
![Image](https://github.com/user-attachments/assets/e17fbab7-8cc7-467e-9adf-fd3179d450d5)
![Image](https://github.com/user-attachments/assets/25723c6d-fece-4e70-a0b2-e5cbac29353a)

on Phantom wallet 
![Image](https://github.com/user-attachments/assets/6f2c05d6-75ac-4456-bad7-cb084eff92b9)

on IOS OneKey wallet 
![Image](https://github.com/user-attachments/assets/979df60d-a964-41ee-919b-04c32b679796)
![Image](https://github.com/user-attachments/assets/25054b3d-8858-475e-baa0-5564a671a011)
![Image](https://github.com/user-attachments/assets/d38ec1ce-adf3-4a27-af9b-438997f937ce)

Device: Samsung Galaxy S23 Ultra
OS: One UI 6.1
Browser: OneKey browser
Android Version: 14

**Comment by limichange** [comment]
We've just released a new version of our app which includes fixes that we believe address the type of issue you were experiencing. Could you please update the app to the latest version and see if that resolves the problem for you? Thanks for your patience!

**Comment by NarineKosyan** [comment]
The error still exists. I checked it in the latest version 5.8.0.
[https://github.com/user-attachments/assets/20c6d520-d696-4af9-b139-d6c9e071a14c](https://github.com/user-attachments/assets/20c6d520-d696-4af9-b139-d6c9e071a14c)
